{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "uni-replicator.fullname" . }}
  labels:
    {{- include "uni-replicator.labels" . | nindent 4 }}
rules:
  {{- range .Values.config.watches }}
  {{- $parts := splitList "/" .apiVersion }}
  - apiGroups:
      - {{ if eq (len $parts) 1 }}""{{ else }}{{ first $parts | quote }}{{ end }}
    resources:
      {{- toYaml .resources | nindent 6 }}
    verbs: ["get", "list", "watch", "patch", "delete"]
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "uni-replicator.fullname" . }}
  labels:
    {{- include "uni-replicator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "uni-replicator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "uni-replicator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
